<?php
$requirements=['PHP 8.2 or newer'=>PHP_VERSION_ID>=80200,'PDO MySQL extension'=>extension_loaded('pdo_mysql'),'Writable storage folder'=>is_writable(ROOT.'/storage'),'HTTPS (or localhost for testing)'=>$https||in_array($_SERVER['SERVER_NAME']??'',['localhost','127.0.0.1','::1'],true)];
$error='';$keyFile=ROOT.'/storage/install-key.php';
if(is_writable(ROOT.'/storage')&&!is_file($keyFile)){$f=fopen($keyFile,'x');if($f){fwrite($f,"<?php return ".var_export(bin2hex(random_bytes(24)),true).";\n");fclose($f);chmod($keyFile,0600);}}
if($_SERVER['REQUEST_METHOD']==='POST'){
 verify_csrf();$lock=null;$c=null;$created=false;
 try{
 if(in_array(false,$requirements,true))throw new RuntimeException('Please resolve the server requirements first.');
 if(!is_file($keyFile)||!hash_equals(require $keyFile,(string)($_POST['install_key']??'')))throw new RuntimeException('The installation key is incorrect. Open storage/install-key.php using your hosting file manager.');
 $lock=fopen(ROOT.'/storage/install.lock','c');if(!$lock||!flock($lock,LOCK_EX))throw new RuntimeException('Could not lock installation.');
 if(is_file(ROOT.'/storage/config.php'))go();
 $host=input('host',1,200);$database=input('database',1,64);$username=input('username',1,100);$port=qty_input('port',65535);
 if(!preg_match('/^[a-zA-Z0-9_.\-]+$/',$host)||!preg_match('/^[a-zA-Z0-9_\-]+$/',$database))throw new RuntimeException('Database host or name contains unsupported characters.');
 $config=['host'=>$host,'port'=>$port,'database'=>$database,'username'=>$username,'password'=>(string)($_POST['db_password']??'')];$pdo=connection($config);$c=$pdo;
 $name=input('name',2,100);$email=email_input();$password=input('password',12,72);if($password!==(string)($_POST['password_confirm']??''))throw new RuntimeException('Administrator passwords do not match.');$site=input('site_name',2,100);$tz=input('timezone',1,80);if(!in_array($tz,DateTimeZone::listIdentifiers(),true))throw new RuntimeException('Select a valid timezone.');
 if(query("SHOW TABLES LIKE 'ot\\_%'")->fetch())throw new RuntimeException('This database already contains OpenTicket tables. Use an empty database or restore the existing installation config.');
 $created=true;foreach(explode(';',file_get_contents(ROOT.'/app/schema.sql')) as $sql){if(trim($sql)!=='')$pdo->exec($sql);}
 $pdo->beginTransaction();query("INSERT INTO ot_users(name,email,password,role) VALUES(?,?,?,'admin')",[$name,$email,password_hash($password,PASSWORD_DEFAULT)]);$uid=(int)$pdo->lastInsertId();foreach(['site_name'=>$site,'timezone'=>$tz,'home_description'=>'Find your people. Discover something new. Your next great experience starts here.','schema_version'=>'1'] as $k=>$v)query('INSERT INTO ot_settings(name,value) VALUES(?,?)',[$k,$v]);$pdo->commit();
 $tmp=ROOT.'/storage/config.'.bin2hex(random_bytes(6)).'.tmp.php';if(file_put_contents($tmp,"<?php\nreturn ".var_export($config,true).";\n",LOCK_EX)===false)throw new RuntimeException('Could not save configuration.');chmod($tmp,0600);if(!rename($tmp,ROOT.'/storage/config.php')){unlink($tmp);throw new RuntimeException('Could not finish configuration.');}
 unlink($keyFile);session_regenerate_id(true);$_SESSION['uid']=$uid;flash('OpenTicket is installed. Create your first event below.');go('admin');
 }catch(Throwable $e){
 if($c&&$c->inTransaction())$c->rollBack();
 if($created&&$c&&!is_file(ROOT.'/storage/config.php')){foreach(['ot_bookings','ot_events','ot_users','ot_settings','ot_throttle'] as $t){try{$c->exec('DROP TABLE IF EXISTS '.$t);}catch(Throwable $ignored){}}}
 unset($GLOBALS['pdo']);$error=$e instanceof RuntimeException&&!($e instanceof PDOException)?$e->getMessage():'Database setup failed. Check the database credentials and CREATE/ALTER/INDEX permissions. No password is displayed.';
 }finally{if(is_resource($lock)){flock($lock,LOCK_UN);fclose($lock);}}
}
header_view('Install');?><section class="install"><div class="eyebrow">WELCOME TO OPENTICKET</div><h1>Your next great event<br>starts here<span>.</span></h1><p>Set up your own ticket-booking website. No terminal commands required.</p><div class="steps"><span>1 · Check hosting</span><span>2 · Connect database</span><span>3 · Create administrator</span></div><div class="requirements"><?php foreach($requirements as $label=>$ok):?><div><?= $ok?'✓':'✕' ?> <?=esc($label)?></div><?php endforeach;?></div><?php if($error):?><p class="error" role="alert"><?=esc($error)?></p><?php endif;?><form method="post" class="panel"><?=csrf_field()?><h2>Confirm this is your server</h2><p>Using your hosting file manager, open <b>storage/install-key.php</b> and copy the code between the quotes. This prevents other visitors from claiming your installation.</p><label>Installation key<input name="install_key" required autocomplete="off"></label><h2>Website details</h2><label>Website name<input name="site_name" required value="OpenTicket" maxlength="100"></label><label>Event timezone<select name="timezone"><?php foreach(DateTimeZone::listIdentifiers() as $tz):?><option <?= $tz==='America/Vancouver'?'selected':'' ?>><?=esc($tz)?></option><?php endforeach;?></select></label><h2>Database connection</h2><p>Create an empty MySQL database and database user in your hosting panel first. The installer creates its tables automatically.</p><div class="row"><label>Database host<input name="host" value="localhost" required></label><label>Port<input name="port" type="number" value="3306" min="1" max="65535" required></label></div><label>Database name<input name="database" required autocomplete="off"></label><label>Database username<input name="username" required autocomplete="off"></label><label>Database password<input name="db_password" type="password" autocomplete="new-password"></label><h2>Administrator account</h2><label>Your name<input name="name" required minlength="2" maxlength="100"></label><label>Email<input name="email" type="email" required></label><div class="row"><label>Password (12–72 characters)<input name="password" type="password" required minlength="12" maxlength="72" autocomplete="new-password"></label><label>Confirm password<input name="password_confirm" type="password" required minlength="12" maxlength="72" autocomplete="new-password"></label></div><button class="button dark" <?=in_array(false,$requirements,true)?'disabled':''?>>Install OpenTicket →</button><p class="fine">This alpha release supports free events. Paid tickets, QR scanning, and email delivery are upcoming features.</p></form></section><?php footer_view();
